# Generated by Django 5.2.4 on 2025-07-10 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerQuizSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('questions', models.JSONField()),
                ('answers', models.JSONField()),
                ('recommendations', models.JSONField()),
                ('reasoning', models.TextField()),
            ],
        ),
    ]
